// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VsfmServiceClient is the client API for VsfmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VsfmServiceClient interface {
	// StartLocalVim starts a Virtualized Infrastructure Manager on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the vsfm/config.yaml
	//   3. all bytes constituting the Virtualized Infrastructure Manager YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalVim(ctx context.Context, opts ...grpc.CallOption) (VsfmService_StartLocalVimClient, error)
	// StartFromPreviousVim starts a new Virtualized Infrastructure Manager based on a previous one.
	// If the previous Virtualized Infrastructure Manager does not have the can-replay condition set this call will result in an error.
	StartFromPreviousVim(ctx context.Context, in *StartFromPreviousVimRequest, opts ...grpc.CallOption) (*StartVimResponse, error)
	// StartVimRequest starts a new Virtualized Infrastructure Manager based on its specification.
	StartVim(ctx context.Context, in *StartVimRequest, opts ...grpc.CallOption) (*StartVimResponse, error)
	// Searches for Virtualized Infrastructure Manager(s) known to this instance
	ListVims(ctx context.Context, in *ListVimsRequest, opts ...grpc.CallOption) (*ListVimsResponse, error)
	// Subscribe listens to new Virtualized Infrastructure Manager(s) updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (VsfmService_SubscribeClient, error)
	// GetVim retrieves details of a single Virtualized Infrastructure Manager
	GetVim(ctx context.Context, in *GetVimRequest, opts ...grpc.CallOption) (*GetVimResponse, error)
	// Listen listens to Virtualized Infrastructure Manager updates and log output of a running Virtualized Infrastructure Manager
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (VsfmService_ListenClient, error)
	// StopVim stops a currently running Virtualized Infrastructure Manager
	StopVim(ctx context.Context, in *StopVimRequest, opts ...grpc.CallOption) (*StopVimResponse, error)
}

type vsfmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVsfmServiceClient(cc grpc.ClientConnInterface) VsfmServiceClient {
	return &vsfmServiceClient{cc}
}

func (c *vsfmServiceClient) StartLocalVim(ctx context.Context, opts ...grpc.CallOption) (VsfmService_StartLocalVimClient, error) {
	stream, err := c.cc.NewStream(ctx, &VsfmService_ServiceDesc.Streams[0], "/v1.VsfmService/StartLocalVim", opts...)
	if err != nil {
		return nil, err
	}
	x := &vsfmServiceStartLocalVimClient{stream}
	return x, nil
}

type VsfmService_StartLocalVimClient interface {
	Send(*StartLocalVimRequest) error
	CloseAndRecv() (*StartVimResponse, error)
	grpc.ClientStream
}

type vsfmServiceStartLocalVimClient struct {
	grpc.ClientStream
}

func (x *vsfmServiceStartLocalVimClient) Send(m *StartLocalVimRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vsfmServiceStartLocalVimClient) CloseAndRecv() (*StartVimResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StartVimResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vsfmServiceClient) StartFromPreviousVim(ctx context.Context, in *StartFromPreviousVimRequest, opts ...grpc.CallOption) (*StartVimResponse, error) {
	out := new(StartVimResponse)
	err := c.cc.Invoke(ctx, "/v1.VsfmService/StartFromPreviousVim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vsfmServiceClient) StartVim(ctx context.Context, in *StartVimRequest, opts ...grpc.CallOption) (*StartVimResponse, error) {
	out := new(StartVimResponse)
	err := c.cc.Invoke(ctx, "/v1.VsfmService/StartVim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vsfmServiceClient) ListVims(ctx context.Context, in *ListVimsRequest, opts ...grpc.CallOption) (*ListVimsResponse, error) {
	out := new(ListVimsResponse)
	err := c.cc.Invoke(ctx, "/v1.VsfmService/ListVims", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vsfmServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (VsfmService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &VsfmService_ServiceDesc.Streams[1], "/v1.VsfmService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &vsfmServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VsfmService_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type vsfmServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *vsfmServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vsfmServiceClient) GetVim(ctx context.Context, in *GetVimRequest, opts ...grpc.CallOption) (*GetVimResponse, error) {
	out := new(GetVimResponse)
	err := c.cc.Invoke(ctx, "/v1.VsfmService/GetVim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vsfmServiceClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (VsfmService_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &VsfmService_ServiceDesc.Streams[2], "/v1.VsfmService/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &vsfmServiceListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VsfmService_ListenClient interface {
	Recv() (*ListenResponse, error)
	grpc.ClientStream
}

type vsfmServiceListenClient struct {
	grpc.ClientStream
}

func (x *vsfmServiceListenClient) Recv() (*ListenResponse, error) {
	m := new(ListenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vsfmServiceClient) StopVim(ctx context.Context, in *StopVimRequest, opts ...grpc.CallOption) (*StopVimResponse, error) {
	out := new(StopVimResponse)
	err := c.cc.Invoke(ctx, "/v1.VsfmService/StopVim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VsfmServiceServer is the server API for VsfmService service.
// All implementations must embed UnimplementedVsfmServiceServer
// for forward compatibility
type VsfmServiceServer interface {
	// StartLocalVim starts a Virtualized Infrastructure Manager on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the vsfm/config.yaml
	//   3. all bytes constituting the Virtualized Infrastructure Manager YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalVim(VsfmService_StartLocalVimServer) error
	// StartFromPreviousVim starts a new Virtualized Infrastructure Manager based on a previous one.
	// If the previous Virtualized Infrastructure Manager does not have the can-replay condition set this call will result in an error.
	StartFromPreviousVim(context.Context, *StartFromPreviousVimRequest) (*StartVimResponse, error)
	// StartVimRequest starts a new Virtualized Infrastructure Manager based on its specification.
	StartVim(context.Context, *StartVimRequest) (*StartVimResponse, error)
	// Searches for Virtualized Infrastructure Manager(s) known to this instance
	ListVims(context.Context, *ListVimsRequest) (*ListVimsResponse, error)
	// Subscribe listens to new Virtualized Infrastructure Manager(s) updates
	Subscribe(*SubscribeRequest, VsfmService_SubscribeServer) error
	// GetVim retrieves details of a single Virtualized Infrastructure Manager
	GetVim(context.Context, *GetVimRequest) (*GetVimResponse, error)
	// Listen listens to Virtualized Infrastructure Manager updates and log output of a running Virtualized Infrastructure Manager
	Listen(*ListenRequest, VsfmService_ListenServer) error
	// StopVim stops a currently running Virtualized Infrastructure Manager
	StopVim(context.Context, *StopVimRequest) (*StopVimResponse, error)
	mustEmbedUnimplementedVsfmServiceServer()
}

// UnimplementedVsfmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVsfmServiceServer struct {
}

func (UnimplementedVsfmServiceServer) StartLocalVim(VsfmService_StartLocalVimServer) error {
	return status.Errorf(codes.Unimplemented, "method StartLocalVim not implemented")
}
func (UnimplementedVsfmServiceServer) StartFromPreviousVim(context.Context, *StartFromPreviousVimRequest) (*StartVimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFromPreviousVim not implemented")
}
func (UnimplementedVsfmServiceServer) StartVim(context.Context, *StartVimRequest) (*StartVimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVim not implemented")
}
func (UnimplementedVsfmServiceServer) ListVims(context.Context, *ListVimsRequest) (*ListVimsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVims not implemented")
}
func (UnimplementedVsfmServiceServer) Subscribe(*SubscribeRequest, VsfmService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedVsfmServiceServer) GetVim(context.Context, *GetVimRequest) (*GetVimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVim not implemented")
}
func (UnimplementedVsfmServiceServer) Listen(*ListenRequest, VsfmService_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedVsfmServiceServer) StopVim(context.Context, *StopVimRequest) (*StopVimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVim not implemented")
}
func (UnimplementedVsfmServiceServer) mustEmbedUnimplementedVsfmServiceServer() {}

// UnsafeVsfmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VsfmServiceServer will
// result in compilation errors.
type UnsafeVsfmServiceServer interface {
	mustEmbedUnimplementedVsfmServiceServer()
}

func RegisterVsfmServiceServer(s grpc.ServiceRegistrar, srv VsfmServiceServer) {
	s.RegisterService(&VsfmService_ServiceDesc, srv)
}

func _VsfmService_StartLocalVim_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VsfmServiceServer).StartLocalVim(&vsfmServiceStartLocalVimServer{stream})
}

type VsfmService_StartLocalVimServer interface {
	SendAndClose(*StartVimResponse) error
	Recv() (*StartLocalVimRequest, error)
	grpc.ServerStream
}

type vsfmServiceStartLocalVimServer struct {
	grpc.ServerStream
}

func (x *vsfmServiceStartLocalVimServer) SendAndClose(m *StartVimResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vsfmServiceStartLocalVimServer) Recv() (*StartLocalVimRequest, error) {
	m := new(StartLocalVimRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _VsfmService_StartFromPreviousVim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFromPreviousVimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VsfmServiceServer).StartFromPreviousVim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VsfmService/StartFromPreviousVim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VsfmServiceServer).StartFromPreviousVim(ctx, req.(*StartFromPreviousVimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VsfmService_StartVim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VsfmServiceServer).StartVim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VsfmService/StartVim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VsfmServiceServer).StartVim(ctx, req.(*StartVimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VsfmService_ListVims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VsfmServiceServer).ListVims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VsfmService/ListVims",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VsfmServiceServer).ListVims(ctx, req.(*ListVimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VsfmService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VsfmServiceServer).Subscribe(m, &vsfmServiceSubscribeServer{stream})
}

type VsfmService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type vsfmServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *vsfmServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VsfmService_GetVim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VsfmServiceServer).GetVim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VsfmService/GetVim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VsfmServiceServer).GetVim(ctx, req.(*GetVimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VsfmService_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VsfmServiceServer).Listen(m, &vsfmServiceListenServer{stream})
}

type VsfmService_ListenServer interface {
	Send(*ListenResponse) error
	grpc.ServerStream
}

type vsfmServiceListenServer struct {
	grpc.ServerStream
}

func (x *vsfmServiceListenServer) Send(m *ListenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VsfmService_StopVim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VsfmServiceServer).StopVim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VsfmService/StopVim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VsfmServiceServer).StopVim(ctx, req.(*StopVimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VsfmService_ServiceDesc is the grpc.ServiceDesc for VsfmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VsfmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VsfmService",
	HandlerType: (*VsfmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFromPreviousVim",
			Handler:    _VsfmService_StartFromPreviousVim_Handler,
		},
		{
			MethodName: "StartVim",
			Handler:    _VsfmService_StartVim_Handler,
		},
		{
			MethodName: "ListVims",
			Handler:    _VsfmService_ListVims_Handler,
		},
		{
			MethodName: "GetVim",
			Handler:    _VsfmService_GetVim_Handler,
		},
		{
			MethodName: "StopVim",
			Handler:    _VsfmService_StopVim_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartLocalVim",
			Handler:       _VsfmService_StartLocalVim_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _VsfmService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Listen",
			Handler:       _VsfmService_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vsfm.proto",
}
